#!/usr/bin/env python3

"""

Not meant for running directly. Just showing basic API functionality.

"""
from lib.model import Model
from lib.model_config import ModelConfig
from lib.model_runner import ModelRunner
from dataclasses import asdict
import json

models: list[ModelConfig] = [
    ModelConfig(
        name="BAAI/bge-large-en-v1.5",
        token_lengths=[100, 200, 500],
        permutations=100,
        runs=100,
    ),
    ModelConfig(
        name="BAAI/bge-base-en-v1.5",
        token_lengths=[100, 200, 500],
        permutations=100,
        runs=100,
    ),
]

for mc in models:
    model = Model(mc, device="auto", local_model_force=False)
    runner = ModelRunner(model=model, model_config=mc)
    # For just printing to console
    runner.run()
    # For saving data - this automatically saves a file but returns a higher level api
    data = runner.data_run()
    # For custom editing
    dictionary_data = [asdict(stat) for stat in data]

    with open("sample-output.json", "w") as f:
        json.dump(dictionary_data, f, default=str, indent=4)
